/************************
 * Unifi Webhook Event Receiver
 * DailySummary.cs
 *
 * Models for the comprehensive daily summary JSON structure generated by the summary lambda.
 * This optimized format enables fast API responses without processing individual event files.
 *
 * Author: Brent Foster
 * Created: 9-7-2025
 ***********************/

using System.Collections.Generic;

namespace UnifiWebhookEventReceiver.Models
{
    /// <summary>
    /// Represents the metadata section of a daily summary file.
    /// </summary>
    public class SummaryMetadata
    {
        public string date { get; set; } = string.Empty;
        public string dateFormatted { get; set; } = string.Empty;
        public string lastUpdated { get; set; } = string.Empty;
        public int totalEvents { get; set; }
    }

    /// <summary>
    /// Represents an individual event in the daily summary.
    /// </summary>
    public class DailySummaryEvent
    {
        public string EventId { get; set; } = string.Empty;
        public long Timestamp { get; set; }
        public string DeviceName { get; set; } = string.Empty;
        public string EventType { get; set; } = string.Empty;
    }

    /// <summary>
    /// Represents the complete daily summary structure generated by the summary lambda.
    /// </summary>
    public class DailySummary
    {
        public SummaryMetadata metadata { get; set; } = new();
        public Dictionary<string, int> eventCounts { get; set; } = new();
        public Dictionary<string, int> deviceCounts { get; set; } = new();
        public Dictionary<string, int> hourlyCounts { get; set; } = new();
        public List<DailySummaryEvent> events { get; set; } = new();
    }
}
